### ISSUE TITLE
Windows已运行成功，遇到几个问题解决办法

### ISSUE THREAD

**Issue by js027** [GuijiAI/HeyGem.ai#53]
肝了2晚，终于允许成功，可以生成视频了。
本人是技术小白，遇到了很多问题，靠大家前面的问题以及deepseek解决的。
以下是一些问题解决办法：

1、首先，拉取源码本地后，在docker安装镜像时，遇到第一个问题
需要对/deploy这个目录 参考 #5  修改docker-compose.yml文件，才可以执行 `docker-compose up -d`
否则会报错：heygem-tts 启动报错 “/opt/conda/envs/python310/bin/python3: No module named tools.api”

2、执行 `docker-compose up -d` 无法下载，这个需要开代理网络。
如果总是下载不好，可以3个容器一个个安装：
`docker pull guiji2025/fun-asr:1.0.2
docker pull guiji2025/fish-speech-ziming:1.0.39
docker pull guiji2025/heygem.ai:0.0.7_sdk_slim`
最后再执行 `docker-compose up -d`。

3、构建脚本npm run build:win 
报错：`Node.js version usingNODE MODULE VERSION 127.This version of Node.js requiresNODE MODULE VERSION 130`
这里进入项目目录，执行这个命令。本地安装 `electron-rebuild  ``和node_modules`工具
前提是安装 Nodejs 18.X  这个必须是 Nodejs 18.X版本才行。
如果还是不行，要拆分执行（deepseek的解答）：
`npm run build   
npm run electron:win `

4、安装好应用后，无法生成视频，一直卡在20%。提示未安装ffmpeg
这里会报错，没有安装CUDA显卡驱动，以及没有安装ffmpeg
`2025-03-08 22:51:27 Notice: ffmpeg is not installed. torchaudio is used to load audio 2025-03-08 22:51:27 If you want to use ffmpeg backend to load audio, please install it by: 2025-03-08 22:51:27 sudo apt install ffmpeg # ubuntu 2025-03-08 22:51:27 # brew install ffmpeg # mac 2025-03-08 22:51:27 transformer is not installed, please install it if you want to use related modules`
这里需要安装CUDA显卡驱动，以及在容器里安装ffmpeg。宿主机上安装没用，需要到容器里安装ffmpeg。
解决办法：在Docker的容器“heygem-asr“通过“Exec”的命令来安ffmpeg
`sudo apt install ffmpeg
ffmpeg -version  # 输出版本信息即安装成功‌`

5、上面几个问题解决了，就是最后生成视频了
这里会报错，显卡内容不足、服务不进行注册的问题
`[app_local.py[line:230]] [WARNING] [ -> 服务不进行注册] 2025-03-08 23:44:38 [2025-03-08 23:44:38] [app_local.py[line:231]] [INFO] [TransDhTask init] 2025-03-08 23:44:43 [2025-03-08 23:44:43] [process.py[line:108]] [INFO] [>>> init_wh_process进程启动] 2025-03-08 23:44:53 2025-03-08 23:44:53.337151184 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'Conv_10' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 2: out of memory ; GPU=0 ; hostname=0aad23e913f0 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_allocator.cc ; line=47 ; expr=cudaMalloc((void**)&p, size);`
这里自己进入heygem-f2f容器文件夹：code/model_lib/里，找到”onnx_model.py”根据deepseek的提示改了显存相关的设置，重启后就ok了。
如图：
![Image](https://github.com/user-attachments/assets/f5a961b8-0149-4747-8dc8-d381f9e53ebc)

最后顺利的开启数字人的创建和视频的生成！最后祝大家玩的愉快！

**Comment by TX165** [comment]
你有没有生成成功的视频，展示一下，还有这个断网可以运行吗？好多人说只开源了一个前端？

**Comment by js027** [comment]
> 你有没有生成成功的视频，展示一下，还有这个断网可以运行吗？好多人说只开源了一个前端？

后端几个容器，其中2个也是其他开源接口，生成的视频效果还是不错。

**Comment by Samge0** [comment]
> 你有没有生成成功的视频，展示一下，还有这个断网可以运行吗？好多人说只开源了一个前端？

目前试了需要联网的情况下使用，docker镜像中存在请求远程的链接（[https://digital-public-dev.obs.myhuaweicloud.com/](https://digital-public-dev.obs.myhuaweicloud.com/)），似乎是生成的音频经过华为云中转暂存，断网的情况下存在请求异常：

![Image](https://github.com/user-attachments/assets/37c3a8d3-b04d-4521-b140-e625b4ce8452)

**Comment by majiabin2020** [comment]
请问如何安装cuda和ffmpeg啊，有没有具体的步骤

**Comment by ball2006** [comment]
> 肝了2晚，终于运行成功，最终创建好数字人生成出视频了。 3080ti 16g显存笔记本，生成30秒的1080p视频，大概90秒。
> 
> 本人是技术小白，遇到了很多问题，靠大家前面的问题以及deepseek解决的。 以下是一些问题解决办法：
> 
> 1、首先，拉取源码本地后，在docker安装镜像时，遇到第一个问题
> 
> > 报错：heygem-tts 启动报错 “/opt/conda/envs/python310/bin/python3: No module named tools.api”
> 
> 处理办法是：需要对/deploy这个目录 参考 [#5](https://github.com/GuijiAI/HeyGem.ai/issues/5) 修改docker-compose.yml文件，才可以执行 `docker-compose up -d`
> 
> 2、执行 `docker-compose up -d` 无法下载，这个需要开代理网络。 如果总是下载不好，可以3个容器一个个安装： `docker pull guiji2025/fun-asr:1.0.2` `docker pull guiji2025/fish-speech-ziming:1.0.39` `docker pull guiji2025/heygem.ai:0.0.7_sdk_slim` 最后再执行 `docker-compose up -d`
> 
> 3、构建脚本npm run build:win
> 
> > 报错：Node.js version usingNODE MODULE VERSION 127.This version of Node.js requiresNODE MODULE VERSION 130
> 
> 这里需要本机安装 Nodejs 18.X 这个必须是 Nodejs 18.X版本才行。 然后进入项目目录，执行这个命令。然后本地安装 `` electron-rebuild ``和node_modules ``工具 如果还是不行，要拆分执行（deepseek的解答）： `npm run build ` `npm run electron:win `
> 
> 4、安装好客户端应用后，又遇到问题：无法生成视频，一直卡在20%。日志提示未安装ffmpeg 这里日志提示是没有安装CUDA显卡驱动，以及没有安装ffmpeg。大概是这样：
> 
> > 2025-03-08 22:51:27 Notice: ffmpeg is not installed. torchaudio is used to load audio 2025-03-08 22:51:27 If you want to use ffmpeg backend to load audio, please install it by: 2025-03-08 22:51:27 sudo apt install ffmpeg # ubuntu 2025-03-08 22:51:27 # brew install ffmpeg # mac 2025-03-08 22:51:27 transformer is not installed, please install it if you want to use related modules
> 
> 这里需要安装CUDA显卡驱动，以及在容器里安装ffmpeg。宿主机上安装没用，需要到容器里安装ffmpeg。 解决办法：在Docker的容器“heygem-asr“通过“Exec”的命令来安ffmpeg `sudo apt install ffmpeg` `ffmpeg -version # 输出版本信息即安装成功‌`
> 
> 5、上面几个问题解决了，就是最后生成视频了 这里会报错，显卡内容不足、服务不进行注册的问题
> 
> > [app_local.py[line:230]] [WARNING] [ -> 服务不进行注册] 2025-03-08 23:44:38 [2025-03-08 23:44:38] [app_local.py[line:231]] [INFO] [TransDhTask init] 2025-03-08 23:44:43 [2025-03-08 23:44:43] [process.py[line:108]] [INFO] [>>> init_wh_process进程启动] 2025-03-08 23:44:53 2025-03-08 23:44:53.337151184 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'Conv_10' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 2: out of memory ; GPU=0 ; hostname=0aad23e913f0 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_allocator.cc ; line=47 ; expr=cudaMalloc((void**)&p, size);
> 
> 这里自己进入heygem-f2f容器文件夹：code/model_lib/里，找到”onnx_model.py”根据deepseek的提示改了显存相关的设置，重启后就ok了。 如图： ![Image](https://github.com/user-attachments/assets/f5a961b8-0149-4747-8dc8-d381f9e53ebc)
> 
> 以及修改后的：docker-compose.yml 文件
> 
> > networks:
> > ai_network:
> > driver: bridge
> 
> services: heygem-tts: image: guiji2025/fish-speech-ziming:1.0.39 container_name: heygem-tts restart: always runtime: nvidia environment: - NVIDIA_VISIBLE_DEVICES=0 - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display ports: - '18180:8080' volumes: - d:/heygem_data/voice/data:/code/data command: /bin/bash -c "sleep 30 && /opt/conda/envs/python310/bin/python3 tools/api_server.py --listen 0.0.0.0:8080" networks: - ai_network heygem-f2f: image: guiji2025/heygem.ai:0.0.7_sdk_slim container_name: heygem-f2f restart: always privileged: true volumes: - d:/heygem_data/face2face:/code/data environment: - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512 deploy: resources: reservations: devices: - capabilities: [gpu] shm_size: '8g' ports: - '8383:8383' command: python /code/app_local.py networks: - ai_network heygem-asr: image: guiji2025/fun-asr:1.0.2 container_name: heygem-asr restart: always runtime: nvidia privileged: true working_dir: /workspace/FunASR/runtime ports: - '10095:10095' volumes: - D:/heygem_data/asr/runtime-resources/models:/workspace/models command: sh /run.sh deploy: resources: reservations: devices: - driver: nvidia count: all capabilities: [gpu] networks: - ai_network
> 
> 最后顺利的开启数字人的创建和视频的生成！ 祝大家玩的愉快！

大佬，您的HeyGem(win版本)执行程序可否借用一下，卡在这儿一天多了，谢谢

**Comment by majiabin2020** [comment]
您的邮件我已经收到了，我会尽快回复您的！

**Comment by js027** [comment]
> cuda有版本要求吗？

cuda没有版本要求，只有Nodejs 是必须18.X

**Comment by majiabin2020** [comment]
> > 请问如何安装cuda和ffmpeg啊，有没有具体的步骤
> 
> 文档里有说明：
> 
> > 确保有英伟达显卡，并正确安装显卡驱动
> > 英伟达驱动下载地址 https://www.nvidia.cn/drivers/lookup/
> 
> 需要注意的是，得到容器里安装ffmpeg

是在 heygem-asr  里面进行安装对吧？

**Comment by fa1c0n4826** [comment]
感谢说明，已成功运行
